API_TOKEN: 
CHAT_DIR: /Users/wingatesv/gen_ai/chat_histories
CHUNK_OVERLAP: 10
CHUNK_SIZE: 512
DOC_DIR: /Users/wingatesv/gen_ai/documents
EMBEDDING_MODEL: BAAI/bge-small-en-v1.5
INTERFACE_MODE: LIGHT
LLM_MODEL: google/gemma-2-2b-it
